// Generated by scripts/render-guides.mjs from micronaut-projects/micronaut-guides.
import rendered from "@/generated/guides.json";
import type { ConfigurationPropertyHint } from "@/scripts/code-hover";

export interface Guide {
  slug: string;
  title: string;
  intro: string;
  categories: string[];
  tags: string[];
  /** Sample project archive, served from `/guides/`. */
  zip: string;
  headings: { id: string; title: string; depth: number }[];
  /** Documented configuration keys the guide's snippets mention. */
  properties: Record<string, ConfigurationPropertyHint>;
  html: string;
}

export const GUIDES_SOURCE = {
  repository: rendered.repository,
  ref: rendered.ref,
  commit: rendered.commit,
};

/** Python guides, newest first. */
export const guides = rendered.guides as unknown as Guide[];

export const guideHref = (guide: Guide) => `/guides/${guide.slug}/`;

export const guideSourceHref = (guide: Guide) =>
  `https://github.com/${rendered.repository}/tree/${rendered.commit || rendered.ref}/guides/${guide.slug}`;
